name: geoxml
description: Package for loading, manipulating, and saving GPS data in GPX and KML format.
version: 2.4.0
homepage: https://github.com/sun-jiao/geoxml/

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  quiver: '>=3.0.0 <4.0.0'
  xml: '>=6.1.0 <=6.2.2'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
