name: geoxml
description: Package for loading, manipulating, and saving GPS data in GPX and KML format.
version: 2.6.0
homepage: https://github.com/sun-jiao/geoxml/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  quiver: '>=3.0.0 <4.0.0'
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
